In [174]:
import numpy as np

In [175]:
initial_position = np.array([['R','N','B','K','Q','B','N','R'], 
                             ['P']*8, 
                             [' ']*8, 
                             [' ']*8, 
                             [' ']*8, 
                             [' ']*8, 
                             ['p']*8, 
                             ['r','n','b','k','q','b','n','r']])
initial_position

array([['R', 'N', 'B', 'K', 'Q', 'B', 'N', 'R'],
       ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['p', 'p', 'p', 'p', 'p', 'p', 'p', 'p'],
       ['r', 'n', 'b', 'k', 'q', 'b', 'n', 'r']], dtype='<U1')

In [176]:
first_move = np.array([[2]*8, 
                       [2]*8, 
                       [0]*8, 
                       [0]*8,
                       [0]*3 + [1] + [0]*4,
                       [0]*8,
                       [1]*3 + [0] + [1]*4,
                       [1]*8 ])
print(first_move, '\n')

second_move = np.array([[2]*8, 
                       [2]*3 + [0] + [2]*4, 
                       [0]*8, 
                       [0]*3 + [2] + [0]*4,
                       [0]*3 + [1] + [0]*4,
                       [0]*8,
                       [1]*3 + [0] + [1]*4,
                       [1]*8 ])
#print(second_move, '\n')

third_move = np.array([[2]*8, 
                       [2]*3 + [0] + [2]*4, 
                       [0]*8, 
                       [0]*3 + [2] + [0]*4,
                       [0]*3 + [1] + [0]*4,
                       [0]*2 + [1] + [0]*5,
                       [1]*3 + [0] + [1]*4,
                       [1]*1 + [0] + [1]*6])
#print(third_move, '\n')

fourth_move = np.array([[2]*1 + [0] + [2]*6, 
                       [2]*3 + [0] + [2]*4, 
                       [0]*2 + [2] + [0]*5, 
                       [0]*3 + [2] + [0]*4,
                       [0]*3 + [1] + [0]*4,
                       [0]*2 + [1] + [0]*5,
                       [1]*3 + [0] + [1]*4,
                       [1]*1 + [0] + [1]*6 ])
#print(fourth_move, '\n')

fifth_move = np.array([[2]*1 + [0] + [2]*6, 
                    [2]*3 + [0] + [2]*4, 
                    [0]*2 + [2] + [0]*5, 
                    [0]*3 + [1] + [0]*4,
                    [0]*3 + [1] + [0]*4,
                    [0]*8,
                    [1]*3 + [0] + [1]*4,
                    [1]*1 + [0] + [1]*6 ])
print(fifth_move, '\n')

queening_move = np.array([[2] + [0] + [2]*6, 
                    [2]*2 + [0]*2 + [2]*4, 
                    [0]*2 + [2] + [0]*5, 
                    [0]*3 + [1] + [0]*4,
                    [0]*3 + [1] + [0]*4,
                    [0]*8,
                    [1]*3 + [0] + [1]*4,
                    [2]*1 + [0] + [1]*6 ])
print(queening_move, '\n')

move_list = [first_move, second_move, third_move, fourth_move, fifth_move, queening_move]

[[2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 1 1]] 

[[2 0 2 2 2 2 2 2]
 [2 2 2 0 2 2 2 2]
 [0 0 2 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 1]
 [1 0 1 1 1 1 1 1]] 

[[2 0 2 2 2 2 2 2]
 [2 2 0 0 2 2 2 2]
 [0 0 2 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1 1]
 [2 0 1 1 1 1 1 1]] 



In [177]:
def get_square_type(pos_square):
    if pos_square == ' ':
        return 0
    if pos_square.lower() == pos_square: # les blancs sont en lower_case
        return 1
    return 2

def is_final_square(move_square, pos_square):
    if move_square == 0:
        return False
    if get_square_type(pos_square) == move_square:
        return False
    return True

def is_capture(final_pos_square):
    return final_pos_square != ' '

def get_queen(final_pos_square):
    if final_pos_square.lower() == final_pos_square: 
        return 'q'
    return 'Q'

def print_move(pos_square, coord, capture, queening):
    piece = ''
    capt = ''
    queen = ''
    if pos_square.lower() != 'p':
        piece = pos_square.upper()
    if capture :
        capt = 'x'
    if queening :
        queen = '-Q'
    column = chr(coord[0] + 97)
    line = coord[1] + 1
    print(piece + capt + str(column) + str(line) + queen)

In [178]:
def new_position(current_position, new_move):
    original_square = [9,9]
    final_square = [9,9]
    capture = False
    for c in range(8):
        for l in range(8):
            move_square = new_move[c,l]
            pos_square = current_position[c,l]
            if move_square == 0 and pos_square != ' ' :
                original_square = (c,l)
            if is_final_square(move_square, pos_square):
                final_square = (c,l)
                capture = is_capture(pos_square)
    current_position[final_square] = current_position[original_square]
    current_position[original_square] = ' '
    # Is a player queening ?
    queening = current_position[final_square].lower() == 'p' and (final_square[0] == 0 or final_square[0] == 7)

    # Print the Move
    print_move(current_position[final_square], final_square, capture, queening)

    # If the player is queening, replace the pawn by the queen
    if queening :
        current_position[final_square] = get_queen(current_position[final_square])

    return current_position

new_position(initial_position.copy(), first_move)

e4


array([['R', 'N', 'B', 'K', 'Q', 'B', 'N', 'R'],
       ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', 'p', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['p', 'p', 'p', ' ', 'p', 'p', 'p', 'p'],
       ['r', 'n', 'b', 'k', 'q', 'b', 'n', 'r']], dtype='<U1')

In [179]:
def show_move(initial_position, move_list): 
    current_position = initial_position
    print(current_position,'\n')
    for move in move_list :
        current_position = new_position(current_position, move)
        print(current_position, '\n')

show_move(initial_position.copy(), move_list)

[['R' 'N' 'B' 'K' 'Q' 'B' 'N' 'R']
 ['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['p' 'p' 'p' 'p' 'p' 'p' 'p' 'p']
 ['r' 'n' 'b' 'k' 'q' 'b' 'n' 'r']] 

e4
[['R' 'N' 'B' 'K' 'Q' 'B' 'N' 'R']
 ['P' 'P' 'P' 'P' 'P' 'P' 'P' 'P']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' 'p' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['p' 'p' 'p' ' ' 'p' 'p' 'p' 'p']
 ['r' 'n' 'b' 'k' 'q' 'b' 'n' 'r']] 

d4
[['R' 'N' 'B' 'K' 'Q' 'B' 'N' 'R']
 ['P' 'P' 'P' ' ' 'P' 'P' 'P' 'P']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' 'P' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' 'p' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['p' 'p' 'p' ' ' 'p' 'p' 'p' 'p']
 ['r' 'n' 'b' 'k' 'q' 'b' 'n' 'r']] 

Nf3
[['R' 'N' 'B' 'K' 'Q' 'B' 'N' 'R']
 ['P' 'P' 'P' ' ' 'P' 'P' 'P' 'P']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' 'P' ' ' ' ' ' ' ' ']
 